/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponse } from './errorResponse';

/**
 * Bad request - validation error
 */
export type BadRequestResponse = ErrorResponse;
