/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

export type Country = {
    /** Unique identifier for the country */
    id: string;
    /**
     * 2-letter ISO country code
     * @pattern ^[A-Z]{2}$
     */
    isoCode: string;
    /**
     * Country name
     * @maxLength 100
     */
    name: string;
    /**
     * ISO code of the currency used by this country
     * @pattern ^[A-Z]{3}$
     */
    currencyIsoCode: string;
    /** Version number */
    version: number;
    /** Whether this is the current active version */
    isCurrent: boolean;
    /** Date from which this version is valid */
    validFrom: string;
    /**
     * Date until which this version is valid (null if currently active)
     * @nullable
     */
    validTo?: string | null;
    /** Creation timestamp */
    createdAt: string;
    /** Last update timestamp */
    updatedAt: string;
};
