/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

export type CreateCurrencyRequest = {
    /**
     * 3-letter ISO currency code
     * @pattern ^[A-Z]{3}$
     */
    isoCode: string;
    /**
     * Currency name
     * @minLength 1
     * @maxLength 100
     */
    name: string;
    /**
     * Currency symbol
     * @minLength 1
     * @maxLength 10
     */
    symbol?: string;
    /** Date from which this currency is valid */
    validFrom?: string;
    /** Date until which this currency is valid */
    validTo?: string;
};
