/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { Country } from './country';
import type { Currency } from './currency';

export type GetCurrenciesIsoCodeHistory200Data = {
    country?: Country;
    itemList?: Currency[];
};
