/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { GetCountriesCurrencyCurrencyIsoCode200Data } from './getCountriesCurrencyCurrencyIsoCode200Data';

export type GetCountriesCurrencyCurrencyIsoCode200 = {
    success?: boolean;
    data?: GetCountriesCurrencyCurrencyIsoCode200Data;
};
