/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { GetCurrencies200Data } from './getCurrencies200Data';

export type GetCurrencies200 = {
    success?: boolean;
    data?: GetCurrencies200Data;
};
