/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { Currency } from './currency';
import type { PageInfo } from './pageInfo';

export type GetCurrencies200Data = {
    itemList?: Currency[];
    pageInfo?: PageInfo;
};
