/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { CountryWithCurrencyName } from './countryWithCurrencyName';
import type { PageInfo } from './pageInfo';

export type GetCountriesCurrencyCurrencyIsoCode200Data = {
    itemList?: CountryWithCurrencyName[];
    pageInfo?: PageInfo;
};
