/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { GetCurrenciesIsoCodeHistory200Data } from './getCurrenciesIsoCodeHistory200Data';

export type GetCurrenciesIsoCodeHistory200 = {
    success?: boolean;
    data?: GetCurrenciesIsoCodeHistory200Data;
};
