/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { CountryWithCurrency } from './countryWithCurrency';
import type { PageInfo } from './pageInfo';

export type GetCountries200Data = {
    itemList?: CountryWithCurrency[];
    pageInfo?: PageInfo;
};
