/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { GetNotificationsUnreadCountEntityType } from './getNotificationsUnreadCountEntityType';
import type { GetNotificationsUnreadCountType } from './getNotificationsUnreadCountType';

export type GetNotificationsUnreadCountParams = {
    /**
     * Filter by notification type
     */
    type?: GetNotificationsUnreadCountType;
    /**
     * Filter by entity type
     */
    entityType?: GetNotificationsUnreadCountEntityType;
};
