/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { GetNotificationsEntityType } from './getNotificationsEntityType';
import type { GetNotificationsType } from './getNotificationsType';

export type GetNotificationsParams = {
    /**
     * Page index (0-based)
     * @minimum 0
     */
    pageIndex?: number;
    /**
     * Number of items per page
     * @minimum 1
     * @maximum 100
     */
    pageSize?: number;
    /**
     * Filter by notification type
     */
    type?: GetNotificationsType;
    /**
     * Filter by entity type
     */
    entityType?: GetNotificationsEntityType;
    /**
     * Filter by read status
     */
    isRead?: boolean;
};
