/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

export type GetNotificationsUnreadCountEntityType =
    (typeof GetNotificationsUnreadCountEntityType)[keyof typeof GetNotificationsUnreadCountEntityType];

 
export const GetNotificationsUnreadCountEntityType = {
    Country: 'Country',
    Currency: 'Currency',
} as const;
