/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

export type GetNotificationsUnreadCount200Data = {
    /** Number of unread notifications */
    unreadCount?: number;
};
