/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { Notification } from './notification';
import type { NotificationPagination } from './notificationPagination';

export type GetNotifications200Data = {
    notifications?: Notification[];
    pagination?: NotificationPagination;
    /** Total number of unread notifications */
    unreadCount?: number;
};
