/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { MarkAllAsReadRequestEntityType } from './markAllAsReadRequestEntityType';
import type { MarkAllAsReadRequestType } from './markAllAsReadRequestType';

export type MarkAllAsReadRequest = {
    /** Filter by notification type */
    type?: MarkAllAsReadRequestType;
    /** Filter by entity type */
    entityType?: MarkAllAsReadRequestEntityType;
};
