/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter by entity type
 */
export type MarkAllAsReadRequestEntityType =
    (typeof MarkAllAsReadRequestEntityType)[keyof typeof MarkAllAsReadRequestEntityType];

 
export const MarkAllAsReadRequestEntityType = {
    Country: 'Country',
    Currency: 'Currency',
} as const;
