/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter by notification type
 */
export type MarkAllAsReadRequestType = (typeof MarkAllAsReadRequestType)[keyof typeof MarkAllAsReadRequestType];

 
export const MarkAllAsReadRequestType = {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    ARCHIVE: 'ARCHIVE',
} as const;
