/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of entity this notification relates to
 */
export type NotificationEntityType = (typeof NotificationEntityType)[keyof typeof NotificationEntityType];

 
export const NotificationEntityType = {
    Country: 'Country',
    Currency: 'Currency',
} as const;
