/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of notification
 */
export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];

 
export const NotificationType = {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    ARCHIVE: 'ARCHIVE',
} as const;
