/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationDetails } from './notificationDetails';
import type { NotificationEntityType } from './notificationEntityType';
import type { NotificationType } from './notificationType';

export type Notification = {
    /** Unique notification identifier */
    id: string;
    /** Type of notification */
    type: NotificationType;
    /** Type of entity this notification relates to */
    entityType: NotificationEntityType;
    /** UUID of the related entity */
    entityId: string;
    /** Identifier of the related entity (e.g., ISO code) */
    entityIdentifier: string;
    /** Human-readable notification message */
    message: string;
    /** Additional details about the notification */
    details?: NotificationDetails;
    /** Whether the notification has been read */
    isRead: boolean;
    /** When the notification was created */
    createdAt: string;
    /** When the notification was last updated */
    updatedAt: string;
};
