/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { PutNotificationsMarkRead200Data } from './putNotificationsMarkRead200Data';

export type PutNotificationsMarkRead200 = {
    success?: boolean;
    data?: PutNotificationsMarkRead200Data;
};
