/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */
import type { PutNotificationsMarkAllRead200Data } from './putNotificationsMarkAllRead200Data';

export type PutNotificationsMarkAllRead200 = {
    success?: boolean;
    data?: PutNotificationsMarkAllRead200Data;
};
