/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * MSWA Project API
 * API for managing currencies and countries with versioning support
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCurrencyRequest = {
    /**
     * Currency name
     * @minLength 1
     * @maxLength 100
     */
    name?: string;
    /** Date from which this currency is valid */
    validFrom?: string;
};
